# https://github.com/yuriyshyyan/k8s-nginx-manifest
apiVersion: apps/v1
kind: Deployment
# Objective 1: Deployment Object Name hello-world
metadata:
  name: hello-world
spec:
  replicas: 1
  # Objective 2: Labels - app: hello-world
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      # Objective 5: Should use the latest nginx:alpine
      containers:
      - name: nginx
        image: nginx:alpine
        # Objective 4: Listen on 8080
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      # Mount ConfigMap as a volume
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
---
# Objective 3: Bonus Service Object to expose via HTTP outside the cluster (LB) 
apiVersion: v1
kind: Service
metadata:
  name: hello-world-lb
spec:
  selector:
    app: hello-world
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer # aweber.yuriys.net
---
# Objecting 3: Expose on 80 on ClusterIP in cluster
apiVersion: v1
kind: Service
metadata:
  name: hello-world-clip
spec:
  selector:
    app: hello-world
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
---
# Objecting 3: Expose on 30080 outside of cluster (NodePort) and in cluster on 80 (ClusterIP)
apiVersion: v1
kind: Service
metadata:
  name: hello-world-np
spec:
  selector:
    app: hello-world
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
  type: NodePort
---
# Objective 6: Define nginx.conf ConfigMap object
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
# Objective 4: Nginx should listen on 8080
data:
  nginx.conf: |
    server {
      listen 8080;
      location / {
        types {}
        default_type text/plain;
        add_header Content-Type text/plain;

        return 200 "Hello Ryan! Hello, world!";
      }
    }
